name: escon_v2
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.2 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  intl: 0.18.1
  hive: 2.2.3
  hive_flutter: ^1.1.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  flutter_test: 
    sdk: flutter

flutter: 
  fonts: 
    - family: Gilroy
      fonts: 
        - asset: assets/fonts/Gilroy-Regular.ttf
        - asset: assets/fonts/Gilroy-Medium.ttf
          weight: 500
        - asset: assets/fonts/Gilroy-ExtraBold.ttf
          weight: 700
  assets: 
    - assets/images/
  uses-material-design: true

